version: '2'
services:
 freeradius:
  image: "fgiana/freeradius3"
  ports:
   - "1812:1812/udp"
   - "1813:1813/udp"
  volumes:
   - "./volumes/raddb/:/opt/freeradius/etc/raddb/"
 auth-test:
  image: "marcelmaatkamp/freeradius"
# build: "docker-alpine-radius/"
  command: "radtest testing password 127.0.0.1 0 netenghack"
  command: "radtest testing password 10.0.0.9 0 netenghack"
  command: "radtest testing password 54.79.18.238 0 netenghack"
