version: '2'
services:
 freeradius:
  image: "marcelmaatkamp/freeradius"
# build: "docker-alpine-radius/"
  ports:
   - "0.0.0.0:1812:1812"
   - "0.0.0.0:1813:1813"
  volumes:
   - "./volumes/raddb/:/etc/raddb/"
 freeradius-test:
  image: "marcelmaatkamp/freeradius"
# build: "docker-alpine-radius/"
  command: "radtest testing password 127.0.0.1 0 netenghack"
  command: "radtest testing password 10.0.0.9 0 netenghack"
  command: "radtest testing password 54.79.18.238 0 netenghack"
