version: '2'

services:

 freeradius:
  image: "marcelmaatkamp/freeradius"
# build: "docker-alpine-radius/"
  ports:
   - "1812:1812/udp"
   - "1813:1813"
   - "18120:18120"
  volumes:
   - "./volumes/clients.conf:/etc/raddb/clients.conf"
   - "./volumes/users:/etc/raddb/users"

 freeradius-test:
  image: "marcelmaatkamp/freeradius"
# build: "docker-alpine-radius/"
  command: "radtest testing password freeradius 0 SECRET"
