version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: netenghack
    volumes:
       - "./volumes/mysql:/var/lib/mysql"
  adminer:
    image: adminer
    ports:
     - 8080:8080
